//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rebar.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ContextHelp_resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContextHelp_resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rebar.Resources.ContextHelp.resources", typeof(ContextHelp_resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AccumulateAdd_Description {
            get {
                return ResourceManager.GetString("AccumulateAdd_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accumulate Add.
        /// </summary>
        internal static string AccumulateAdd_Name {
            get {
                return ResourceManager.GetString("AccumulateAdd_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x reference.
        /// </summary>
        internal static string AccumulateAdd_operand1Ref_in_Name {
            get {
                return ResourceManager.GetString("AccumulateAdd_operand1Ref_in_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x reference.
        /// </summary>
        internal static string AccumulateAdd_operand1Ref_out_Name {
            get {
                return ResourceManager.GetString("AccumulateAdd_operand1Ref_out_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y reference.
        /// </summary>
        internal static string AccumulateAdd_operand2Ref_in_Name {
            get {
                return ResourceManager.GetString("AccumulateAdd_operand2Ref_in_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y reference.
        /// </summary>
        internal static string AccumulateAdd_operand2Ref_out_Name {
            get {
                return ResourceManager.GetString("AccumulateAdd_operand2Ref_out_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AccumulateAnd_Description {
            get {
                return ResourceManager.GetString("AccumulateAnd_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accumulate And.
        /// </summary>
        internal static string AccumulateAnd_Name {
            get {
                return ResourceManager.GetString("AccumulateAnd_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x reference.
        /// </summary>
        internal static string AccumulateAnd_operand1Ref_in_Name {
            get {
                return ResourceManager.GetString("AccumulateAnd_operand1Ref_in_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x reference.
        /// </summary>
        internal static string AccumulateAnd_operand1Ref_out_Name {
            get {
                return ResourceManager.GetString("AccumulateAnd_operand1Ref_out_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y reference.
        /// </summary>
        internal static string AccumulateAnd_operand2Ref_in_Name {
            get {
                return ResourceManager.GetString("AccumulateAnd_operand2Ref_in_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y reference.
        /// </summary>
        internal static string AccumulateAnd_operand2Ref_out_Name {
            get {
                return ResourceManager.GetString("AccumulateAnd_operand2Ref_out_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AccumulateDivide_Description {
            get {
                return ResourceManager.GetString("AccumulateDivide_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accumulate Divide.
        /// </summary>
        internal static string AccumulateDivide_Name {
            get {
                return ResourceManager.GetString("AccumulateDivide_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x reference.
        /// </summary>
        internal static string AccumulateDivide_operand1Ref_in_Name {
            get {
                return ResourceManager.GetString("AccumulateDivide_operand1Ref_in_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x reference.
        /// </summary>
        internal static string AccumulateDivide_operand1Ref_out_Name {
            get {
                return ResourceManager.GetString("AccumulateDivide_operand1Ref_out_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y reference.
        /// </summary>
        internal static string AccumulateDivide_operand2Ref_in_Name {
            get {
                return ResourceManager.GetString("AccumulateDivide_operand2Ref_in_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y reference.
        /// </summary>
        internal static string AccumulateDivide_operand2Ref_out_Name {
            get {
                return ResourceManager.GetString("AccumulateDivide_operand2Ref_out_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AccumulateIncrement_Description {
            get {
                return ResourceManager.GetString("AccumulateIncrement_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accumulate Increment.
        /// </summary>
        internal static string AccumulateIncrement_Name {
            get {
                return ResourceManager.GetString("AccumulateIncrement_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x reference.
        /// </summary>
        internal static string AccumulateIncrement_operandRef_in_Name {
            get {
                return ResourceManager.GetString("AccumulateIncrement_operandRef_in_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x reference.
        /// </summary>
        internal static string AccumulateIncrement_operandRef_out_Name {
            get {
                return ResourceManager.GetString("AccumulateIncrement_operandRef_out_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AccumulateMultiply_Description {
            get {
                return ResourceManager.GetString("AccumulateMultiply_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accumulate Multiply.
        /// </summary>
        internal static string AccumulateMultiply_Name {
            get {
                return ResourceManager.GetString("AccumulateMultiply_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x reference.
        /// </summary>
        internal static string AccumulateMultiply_operand1Ref_in_Name {
            get {
                return ResourceManager.GetString("AccumulateMultiply_operand1Ref_in_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x reference.
        /// </summary>
        internal static string AccumulateMultiply_operand1Ref_out_Name {
            get {
                return ResourceManager.GetString("AccumulateMultiply_operand1Ref_out_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y reference.
        /// </summary>
        internal static string AccumulateMultiply_operand2Ref_in_Name {
            get {
                return ResourceManager.GetString("AccumulateMultiply_operand2Ref_in_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y reference.
        /// </summary>
        internal static string AccumulateMultiply_operand2Ref_out_Name {
            get {
                return ResourceManager.GetString("AccumulateMultiply_operand2Ref_out_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AccumulateNot_Description {
            get {
                return ResourceManager.GetString("AccumulateNot_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accumulate Not.
        /// </summary>
        internal static string AccumulateNot_Name {
            get {
                return ResourceManager.GetString("AccumulateNot_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x reference.
        /// </summary>
        internal static string AccumulateNot_operandRef_in_Name {
            get {
                return ResourceManager.GetString("AccumulateNot_operandRef_in_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x reference.
        /// </summary>
        internal static string AccumulateNot_operandRef_out_Name {
            get {
                return ResourceManager.GetString("AccumulateNot_operandRef_out_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AccumulateOr_Description {
            get {
                return ResourceManager.GetString("AccumulateOr_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accumulate Or.
        /// </summary>
        internal static string AccumulateOr_Name {
            get {
                return ResourceManager.GetString("AccumulateOr_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x reference.
        /// </summary>
        internal static string AccumulateOr_operand1Ref_in_Name {
            get {
                return ResourceManager.GetString("AccumulateOr_operand1Ref_in_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x reference.
        /// </summary>
        internal static string AccumulateOr_operand1Ref_out_Name {
            get {
                return ResourceManager.GetString("AccumulateOr_operand1Ref_out_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y reference.
        /// </summary>
        internal static string AccumulateOr_operand2Ref_in_Name {
            get {
                return ResourceManager.GetString("AccumulateOr_operand2Ref_in_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y reference.
        /// </summary>
        internal static string AccumulateOr_operand2Ref_out_Name {
            get {
                return ResourceManager.GetString("AccumulateOr_operand2Ref_out_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x | y.
        /// </summary>
        internal static string AccumulateOr_result_Name {
            get {
                return ResourceManager.GetString("AccumulateOr_result_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accumulate Xor.
        /// </summary>
        internal static string AccumulateXor_Name {
            get {
                return ResourceManager.GetString("AccumulateXor_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x reference.
        /// </summary>
        internal static string AccumulateXor_operand1Ref_in_Name {
            get {
                return ResourceManager.GetString("AccumulateXor_operand1Ref_in_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x reference.
        /// </summary>
        internal static string AccumulateXor_operand1Ref_out_Name {
            get {
                return ResourceManager.GetString("AccumulateXor_operand1Ref_out_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y reference.
        /// </summary>
        internal static string AccumulateXor_operand2Ref_in_Name {
            get {
                return ResourceManager.GetString("AccumulateXor_operand2Ref_in_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y reference.
        /// </summary>
        internal static string AccumulateXor_operand2Ref_out_Name {
            get {
                return ResourceManager.GetString("AccumulateXor_operand2Ref_out_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Add_Description {
            get {
                return ResourceManager.GetString("Add_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add_Name {
            get {
                return ResourceManager.GetString("Add_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x reference.
        /// </summary>
        internal static string Add_operand1Ref_in_Name {
            get {
                return ResourceManager.GetString("Add_operand1Ref_in_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x reference.
        /// </summary>
        internal static string Add_operand1Ref_out_Name {
            get {
                return ResourceManager.GetString("Add_operand1Ref_out_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y reference.
        /// </summary>
        internal static string Add_operand2Ref_in_Name {
            get {
                return ResourceManager.GetString("Add_operand2Ref_in_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y reference.
        /// </summary>
        internal static string Add_operand2Ref_out_Name {
            get {
                return ResourceManager.GetString("Add_operand2Ref_out_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x + y.
        /// </summary>
        internal static string Add_result_Name {
            get {
                return ResourceManager.GetString("Add_result_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string And_Description {
            get {
                return ResourceManager.GetString("And_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And.
        /// </summary>
        internal static string And_Name {
            get {
                return ResourceManager.GetString("And_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x reference.
        /// </summary>
        internal static string And_operand1Ref_in_Name {
            get {
                return ResourceManager.GetString("And_operand1Ref_in_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x reference.
        /// </summary>
        internal static string And_operand1Ref_out_Name {
            get {
                return ResourceManager.GetString("And_operand1Ref_out_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y reference.
        /// </summary>
        internal static string And_operand2Ref_in_Name {
            get {
                return ResourceManager.GetString("And_operand2Ref_in_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y reference.
        /// </summary>
        internal static string And_operand2Ref_out_Name {
            get {
                return ResourceManager.GetString("And_operand2Ref_out_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x &amp; y.
        /// </summary>
        internal static string And_result_Name {
            get {
                return ResourceManager.GetString("And_result_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assignee reference.
        /// </summary>
        internal static string AssignNode_assigneeRef_in_Name {
            get {
                return ResourceManager.GetString("AssignNode_assigneeRef_in_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to assignee reference.
        /// </summary>
        internal static string AssignNode_assigneeRef_out_Name {
            get {
                return ResourceManager.GetString("AssignNode_assigneeRef_out_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AssignNode_Description {
            get {
                return ResourceManager.GetString("AssignNode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign.
        /// </summary>
        internal static string AssignNode_Name {
            get {
                return ResourceManager.GetString("AssignNode_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value.
        /// </summary>
        internal static string AssignNode_value_Name {
            get {
                return ResourceManager.GetString("AssignNode_value_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrow Tunnel.
        /// </summary>
        internal static string BorrowTunnel_Name {
            get {
                return ResourceManager.GetString("BorrowTunnel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BorrrowTunnel_Description {
            get {
                return ResourceManager.GetString("BorrrowTunnel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to copy.
        /// </summary>
        internal static string CreateCopyNode_copy_Name {
            get {
                return ResourceManager.GetString("CreateCopyNode_copy_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CreateCopyNode_Description {
            get {
                return ResourceManager.GetString("CreateCopyNode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Copy.
        /// </summary>
        internal static string CreateCopyNode_Name {
            get {
                return ResourceManager.GetString("CreateCopyNode_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value reference.
        /// </summary>
        internal static string CreateCopyNode_valueRef_in_Name {
            get {
                return ResourceManager.GetString("CreateCopyNode_valueRef_in_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value reference.
        /// </summary>
        internal static string CreateCopyNode_valueRef_out_Name {
            get {
                return ResourceManager.GetString("CreateCopyNode_valueRef_out_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cell.
        /// </summary>
        internal static string CreateLockingCell_cell_Name {
            get {
                return ResourceManager.GetString("CreateLockingCell_cell_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CreateLockingCell_Description {
            get {
                return ResourceManager.GetString("CreateLockingCell_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Locking Cell.
        /// </summary>
        internal static string CreateLockingCell_Name {
            get {
                return ResourceManager.GetString("CreateLockingCell_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value.
        /// </summary>
        internal static string CreateLockingCell_value_Name {
            get {
                return ResourceManager.GetString("CreateLockingCell_value_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cell.
        /// </summary>
        internal static string CreateNonLockingCell_cell_Name {
            get {
                return ResourceManager.GetString("CreateNonLockingCell_cell_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CreateNonLockingCell_Description {
            get {
                return ResourceManager.GetString("CreateNonLockingCell_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Non-Locking Cell.
        /// </summary>
        internal static string CreateNonLockingCell_Name {
            get {
                return ResourceManager.GetString("CreateNonLockingCell_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value.
        /// </summary>
        internal static string CreateNonLockingCell_value_Name {
            get {
                return ResourceManager.GetString("CreateNonLockingCell_value_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Divide_Description {
            get {
                return ResourceManager.GetString("Divide_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divide.
        /// </summary>
        internal static string Divide_Name {
            get {
                return ResourceManager.GetString("Divide_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x reference.
        /// </summary>
        internal static string Divide_operand1Ref_in_Name {
            get {
                return ResourceManager.GetString("Divide_operand1Ref_in_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x reference.
        /// </summary>
        internal static string Divide_operand1Ref_out_Name {
            get {
                return ResourceManager.GetString("Divide_operand1Ref_out_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y reference.
        /// </summary>
        internal static string Divide_operand2Ref_in_Name {
            get {
                return ResourceManager.GetString("Divide_operand2Ref_in_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y reference.
        /// </summary>
        internal static string Divide_operand2Ref_out_Name {
            get {
                return ResourceManager.GetString("Divide_operand2Ref_out_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x / y.
        /// </summary>
        internal static string Divide_result_Name {
            get {
                return ResourceManager.GetString("Divide_result_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DropNode_Description {
            get {
                return ResourceManager.GetString("DropNode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop.
        /// </summary>
        internal static string DropNode_Name {
            get {
                return ResourceManager.GetString("DropNode_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value.
        /// </summary>
        internal static string DropNode_value_Name {
            get {
                return ResourceManager.GetString("DropNode_value_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Equal_Description {
            get {
                return ResourceManager.GetString("Equal_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equal.
        /// </summary>
        internal static string Equal_Name {
            get {
                return ResourceManager.GetString("Equal_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x reference.
        /// </summary>
        internal static string Equal_operand1Ref_in_Name {
            get {
                return ResourceManager.GetString("Equal_operand1Ref_in_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x reference.
        /// </summary>
        internal static string Equal_operand1Ref_out_Name {
            get {
                return ResourceManager.GetString("Equal_operand1Ref_out_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y reference.
        /// </summary>
        internal static string Equal_operand2Ref_in_Name {
            get {
                return ResourceManager.GetString("Equal_operand2Ref_in_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y reference.
        /// </summary>
        internal static string Equal_operand2Ref_out_Name {
            get {
                return ResourceManager.GetString("Equal_operand2Ref_out_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x == y.
        /// </summary>
        internal static string Equal_result_Name {
            get {
                return ResourceManager.GetString("Equal_result_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ExchangeValues_Description {
            get {
                return ResourceManager.GetString("ExchangeValues_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exchangee reference 1.
        /// </summary>
        internal static string ExchangeValues_exchangeeRef1_in_Name {
            get {
                return ResourceManager.GetString("ExchangeValues_exchangeeRef1_in_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exchangee reference 1.
        /// </summary>
        internal static string ExchangeValues_exchangeeRef1_out_Name {
            get {
                return ResourceManager.GetString("ExchangeValues_exchangeeRef1_out_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exchangee reference 2.
        /// </summary>
        internal static string ExchangeValues_exchangeeRef2_in_Name {
            get {
                return ResourceManager.GetString("ExchangeValues_exchangeeRef2_in_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exchangee reference 2.
        /// </summary>
        internal static string ExchangeValues_exchangeeRef2_out_Name {
            get {
                return ResourceManager.GetString("ExchangeValues_exchangeeRef2_out_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Values.
        /// </summary>
        internal static string ExchangeValues_Name {
            get {
                return ResourceManager.GetString("ExchangeValues_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FlatSequence_Description {
            get {
                return ResourceManager.GetString("FlatSequence_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flat Sequence.
        /// </summary>
        internal static string FlatSequence_Name {
            get {
                return ResourceManager.GetString("FlatSequence_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FlatSequenceTerminateLifetimeTunnel_Description {
            get {
                return ResourceManager.GetString("FlatSequenceTerminateLifetimeTunnel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminate Lifetime Tunnel.
        /// </summary>
        internal static string FlatSequenceTerminateLifetimeTunnel_Name {
            get {
                return ResourceManager.GetString("FlatSequenceTerminateLifetimeTunnel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string GreaterEqual_Description {
            get {
                return ResourceManager.GetString("GreaterEqual_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greater Than Or Equal.
        /// </summary>
        internal static string GreaterEqual_Name {
            get {
                return ResourceManager.GetString("GreaterEqual_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x reference.
        /// </summary>
        internal static string GreaterEqual_operand1Ref_in_Name {
            get {
                return ResourceManager.GetString("GreaterEqual_operand1Ref_in_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x reference.
        /// </summary>
        internal static string GreaterEqual_operand1Ref_out_Name {
            get {
                return ResourceManager.GetString("GreaterEqual_operand1Ref_out_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y reference.
        /// </summary>
        internal static string GreaterEqual_operand2Ref_in_Name {
            get {
                return ResourceManager.GetString("GreaterEqual_operand2Ref_in_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y reference.
        /// </summary>
        internal static string GreaterEqual_operand2Ref_out_Name {
            get {
                return ResourceManager.GetString("GreaterEqual_operand2Ref_out_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x &gt;= y.
        /// </summary>
        internal static string GreaterEqual_result_Name {
            get {
                return ResourceManager.GetString("GreaterEqual_result_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string GreaterThan_Description {
            get {
                return ResourceManager.GetString("GreaterThan_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greater Than.
        /// </summary>
        internal static string GreaterThan_Name {
            get {
                return ResourceManager.GetString("GreaterThan_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x reference.
        /// </summary>
        internal static string GreaterThan_operand1Ref_in_Name {
            get {
                return ResourceManager.GetString("GreaterThan_operand1Ref_in_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x reference.
        /// </summary>
        internal static string GreaterThan_operand1Ref_out_Name {
            get {
                return ResourceManager.GetString("GreaterThan_operand1Ref_out_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y reference.
        /// </summary>
        internal static string GreaterThan_operand2Ref_in_Name {
            get {
                return ResourceManager.GetString("GreaterThan_operand2Ref_in_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y reference.
        /// </summary>
        internal static string GreaterThan_operand2Ref_out_Name {
            get {
                return ResourceManager.GetString("GreaterThan_operand2Ref_out_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x &gt; y.
        /// </summary>
        internal static string GreaterThan_result_Name {
            get {
                return ResourceManager.GetString("GreaterThan_result_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ImmutableBorrowNode_Description {
            get {
                return ResourceManager.GetString("ImmutableBorrowNode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immutable Borrow.
        /// </summary>
        internal static string ImmutableBorrowNode_Name {
            get {
                return ResourceManager.GetString("ImmutableBorrowNode_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reference out.
        /// </summary>
        internal static string ImmutableBorrowNode_reference_out_Name {
            get {
                return ResourceManager.GetString("ImmutableBorrowNode_reference out_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value in.
        /// </summary>
        internal static string ImmutableBorrowNode_value_in_Name {
            get {
                return ResourceManager.GetString("ImmutableBorrowNode_value in_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ImmutablePassthroughNode_Description {
            get {
                return ResourceManager.GetString("ImmutablePassthroughNode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immutable Passthrough.
        /// </summary>
        internal static string ImmutablePassthroughNode_Name {
            get {
                return ResourceManager.GetString("ImmutablePassthroughNode_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value reference.
        /// </summary>
        internal static string ImmutablePassthroughNode_valueRef_in_Name {
            get {
                return ResourceManager.GetString("ImmutablePassthroughNode_valueRef_in_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value reference.
        /// </summary>
        internal static string ImmutablePassthroughNode_valueRef_out_Name {
            get {
                return ResourceManager.GetString("ImmutablePassthroughNode_valueRef_out_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Increment_Description {
            get {
                return ResourceManager.GetString("Increment_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increment.
        /// </summary>
        internal static string Increment_Name {
            get {
                return ResourceManager.GetString("Increment_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x reference.
        /// </summary>
        internal static string Increment_operandRef_in_Name {
            get {
                return ResourceManager.GetString("Increment_operandRef_in_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x reference.
        /// </summary>
        internal static string Increment_operandRef_out_Name {
            get {
                return ResourceManager.GetString("Increment_operandRef_out_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x + 1.
        /// </summary>
        internal static string Increment_result_Name {
            get {
                return ResourceManager.GetString("Increment_result_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LessEqual_Description {
            get {
                return ResourceManager.GetString("LessEqual_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less Than Or Equal.
        /// </summary>
        internal static string LessEqual_Name {
            get {
                return ResourceManager.GetString("LessEqual_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x reference.
        /// </summary>
        internal static string LessEqual_operand1Ref_in_Name {
            get {
                return ResourceManager.GetString("LessEqual_operand1Ref_in_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x reference.
        /// </summary>
        internal static string LessEqual_operand1Ref_out_Name {
            get {
                return ResourceManager.GetString("LessEqual_operand1Ref_out_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y reference.
        /// </summary>
        internal static string LessEqual_operand2Ref_in_Name {
            get {
                return ResourceManager.GetString("LessEqual_operand2Ref_in_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y reference.
        /// </summary>
        internal static string LessEqual_operand2Ref_out_Name {
            get {
                return ResourceManager.GetString("LessEqual_operand2Ref_out_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x &lt;= y.
        /// </summary>
        internal static string LessEqual_result_Name {
            get {
                return ResourceManager.GetString("LessEqual_result_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LessThan_Description {
            get {
                return ResourceManager.GetString("LessThan_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less Than.
        /// </summary>
        internal static string LessThan_Name {
            get {
                return ResourceManager.GetString("LessThan_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x reference.
        /// </summary>
        internal static string LessThan_operand1Ref_in_Name {
            get {
                return ResourceManager.GetString("LessThan_operand1Ref_in_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x reference.
        /// </summary>
        internal static string LessThan_operand1Ref_out_Name {
            get {
                return ResourceManager.GetString("LessThan_operand1Ref_out_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y reference.
        /// </summary>
        internal static string LessThan_operand2Ref_in_Name {
            get {
                return ResourceManager.GetString("LessThan_operand2Ref_in_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y reference.
        /// </summary>
        internal static string LessThan_operand2Ref_out_Name {
            get {
                return ResourceManager.GetString("LessThan_operand2Ref_out_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x &lt; y.
        /// </summary>
        internal static string LessThan_result_Name {
            get {
                return ResourceManager.GetString("LessThan_result_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LockTunnel_Description {
            get {
                return ResourceManager.GetString("LockTunnel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Tunnel.
        /// </summary>
        internal static string LockTunnel_Name {
            get {
                return ResourceManager.GetString("LockTunnel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Loop_Description {
            get {
                return ResourceManager.GetString("Loop_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop.
        /// </summary>
        internal static string Loop_Name {
            get {
                return ResourceManager.GetString("Loop_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LoopBorrowTunnel_Description {
            get {
                return ResourceManager.GetString("LoopBorrowTunnel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrow Tunnel.
        /// </summary>
        internal static string LoopBorrowTunnel_Name {
            get {
                return ResourceManager.GetString("LoopBorrowTunnel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LoopConditionTunnel_Description {
            get {
                return ResourceManager.GetString("LoopConditionTunnel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop Condition.
        /// </summary>
        internal static string LoopConditionTunnel_Name {
            get {
                return ResourceManager.GetString("LoopConditionTunnel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LoopIterateTunnel_Description {
            get {
                return ResourceManager.GetString("LoopIterateTunnel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iterate Tunnel.
        /// </summary>
        internal static string LoopIterateTunnel_Name {
            get {
                return ResourceManager.GetString("LoopIterateTunnel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LoopTerminateLifetimeTunnel_Description {
            get {
                return ResourceManager.GetString("LoopTerminateLifetimeTunnel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminate Lifetime Tunnel.
        /// </summary>
        internal static string LoopTerminateLifetimeTunnel_Name {
            get {
                return ResourceManager.GetString("LoopTerminateLifetimeTunnel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LoopTunnel_Description {
            get {
                return ResourceManager.GetString("LoopTunnel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tunnel.
        /// </summary>
        internal static string LoopTunnel_Name {
            get {
                return ResourceManager.GetString("LoopTunnel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Multiply_Description {
            get {
                return ResourceManager.GetString("Multiply_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiply.
        /// </summary>
        internal static string Multiply_Name {
            get {
                return ResourceManager.GetString("Multiply_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x reference.
        /// </summary>
        internal static string Multiply_operand1Ref_in_Name {
            get {
                return ResourceManager.GetString("Multiply_operand1Ref_in_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x reference.
        /// </summary>
        internal static string Multiply_operand1Ref_out_Name {
            get {
                return ResourceManager.GetString("Multiply_operand1Ref_out_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y reference.
        /// </summary>
        internal static string Multiply_operand2Ref_in_Name {
            get {
                return ResourceManager.GetString("Multiply_operand2Ref_in_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y reference.
        /// </summary>
        internal static string Multiply_operand2Ref_out_Name {
            get {
                return ResourceManager.GetString("Multiply_operand2Ref_out_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x * y.
        /// </summary>
        internal static string Multiply_result_Name {
            get {
                return ResourceManager.GetString("Multiply_result_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MutablePassthroughNode_Description {
            get {
                return ResourceManager.GetString("MutablePassthroughNode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mutable Passthrough.
        /// </summary>
        internal static string MutablePassthroughNode_Name {
            get {
                return ResourceManager.GetString("MutablePassthroughNode_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value reference.
        /// </summary>
        internal static string MutablePassthroughNode_valueRef_in_Name {
            get {
                return ResourceManager.GetString("MutablePassthroughNode_valueRef_in_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value reference.
        /// </summary>
        internal static string MutablePassthroughNode_valueRef_out_Name {
            get {
                return ResourceManager.GetString("MutablePassthroughNode_valueRef_out_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NoneConstructorNode_Description {
            get {
                return ResourceManager.GetString("NoneConstructorNode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None Constructor.
        /// </summary>
        internal static string NoneConstructorNode_Name {
            get {
                return ResourceManager.GetString("NoneConstructorNode_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to option.
        /// </summary>
        internal static string NoneConstructorNode_option_Name {
            get {
                return ResourceManager.GetString("NoneConstructorNode_option_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Not_Description {
            get {
                return ResourceManager.GetString("Not_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not.
        /// </summary>
        internal static string Not_Name {
            get {
                return ResourceManager.GetString("Not_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x reference.
        /// </summary>
        internal static string Not_operandRef_in_Name {
            get {
                return ResourceManager.GetString("Not_operandRef_in_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x reference.
        /// </summary>
        internal static string Not_operandRef_out_Name {
            get {
                return ResourceManager.GetString("Not_operandRef_out_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOT x.
        /// </summary>
        internal static string Not_result_Name {
            get {
                return ResourceManager.GetString("Not_result_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NotEqual_Description {
            get {
                return ResourceManager.GetString("NotEqual_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Equal.
        /// </summary>
        internal static string NotEqual_Name {
            get {
                return ResourceManager.GetString("NotEqual_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x reference.
        /// </summary>
        internal static string NotEqual_operand1Ref_in_Name {
            get {
                return ResourceManager.GetString("NotEqual_operand1Ref_in_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x reference.
        /// </summary>
        internal static string NotEqual_operand1Ref_out_Name {
            get {
                return ResourceManager.GetString("NotEqual_operand1Ref_out_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y reference.
        /// </summary>
        internal static string NotEqual_operand2Ref_in_Name {
            get {
                return ResourceManager.GetString("NotEqual_operand2Ref_in_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y reference.
        /// </summary>
        internal static string NotEqual_operand2Ref_out_Name {
            get {
                return ResourceManager.GetString("NotEqual_operand2Ref_out_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x != y.
        /// </summary>
        internal static string NotEqual_result_Name {
            get {
                return ResourceManager.GetString("NotEqual_result_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string OpenFileHandle_Description {
            get {
                return ResourceManager.GetString("OpenFileHandle_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file handle.
        /// </summary>
        internal static string OpenFileHandle_fileHandle_Name {
            get {
                return ResourceManager.GetString("OpenFileHandle_fileHandle_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to path reference.
        /// </summary>
        internal static string OpenFileHandle_filePathRef_in_Name {
            get {
                return ResourceManager.GetString("OpenFileHandle_filePathRef_in_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to path reference.
        /// </summary>
        internal static string OpenFileHandle_filePathRef_out_Name {
            get {
                return ResourceManager.GetString("OpenFileHandle_filePathRef_out_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File Handle.
        /// </summary>
        internal static string OpenFileHandle_Name {
            get {
                return ResourceManager.GetString("OpenFileHandle_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Or_Description {
            get {
                return ResourceManager.GetString("Or_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        internal static string Or_Name {
            get {
                return ResourceManager.GetString("Or_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x reference.
        /// </summary>
        internal static string Or_operand1Ref_in_Name {
            get {
                return ResourceManager.GetString("Or_operand1Ref_in_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x reference.
        /// </summary>
        internal static string Or_operand1Ref_out_Name {
            get {
                return ResourceManager.GetString("Or_operand1Ref_out_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y reference.
        /// </summary>
        internal static string Or_operand2Ref_in_Name {
            get {
                return ResourceManager.GetString("Or_operand2Ref_in_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y reference.
        /// </summary>
        internal static string Or_operand2Ref_out_Name {
            get {
                return ResourceManager.GetString("Or_operand2Ref_out_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x | y.
        /// </summary>
        internal static string Or_result_Name {
            get {
                return ResourceManager.GetString("Or_result_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Output_Description {
            get {
                return ResourceManager.GetString("Output_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        internal static string Output_Name {
            get {
                return ResourceManager.GetString("Output_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value reference.
        /// </summary>
        internal static string Output_valueRef_in_Name {
            get {
                return ResourceManager.GetString("Output_valueRef_in_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value reference.
        /// </summary>
        internal static string Output_valueRef_out_Name {
            get {
                return ResourceManager.GetString("Output_valueRef_out_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Range_Description {
            get {
                return ResourceManager.GetString("Range_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to high value (exclusive).
        /// </summary>
        internal static string Range_highValue_Name {
            get {
                return ResourceManager.GetString("Range_highValue_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to low value (inclusive).
        /// </summary>
        internal static string Range_lowValue_Name {
            get {
                return ResourceManager.GetString("Range_lowValue_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range.
        /// </summary>
        internal static string Range_Name {
            get {
                return ResourceManager.GetString("Range_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to range.
        /// </summary>
        internal static string Range_range_Name {
            get {
                return ResourceManager.GetString("Range_range_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SelectReferenceNode_Description {
            get {
                return ResourceManager.GetString("SelectReferenceNode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false value reference.
        /// </summary>
        internal static string SelectReferenceNode_falseValueRef_Name {
            get {
                return ResourceManager.GetString("SelectReferenceNode_falseValueRef_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Reference.
        /// </summary>
        internal static string SelectReferenceNode_Name {
            get {
                return ResourceManager.GetString("SelectReferenceNode_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selected value reference.
        /// </summary>
        internal static string SelectReferenceNode_selectedValueRef_Name {
            get {
                return ResourceManager.GetString("SelectReferenceNode_selectedValueRef_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selector reference.
        /// </summary>
        internal static string SelectReferenceNode_selectorRef_in_Name {
            get {
                return ResourceManager.GetString("SelectReferenceNode_selectorRef_in_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selector reference.
        /// </summary>
        internal static string SelectReferenceNode_selectorRef_out_Name {
            get {
                return ResourceManager.GetString("SelectReferenceNode_selectorRef_out_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true value reference.
        /// </summary>
        internal static string SelectReferenceNode_trueValueRef_Name {
            get {
                return ResourceManager.GetString("SelectReferenceNode_trueValueRef_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SomeConstructorNode_Description {
            get {
                return ResourceManager.GetString("SomeConstructorNode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some Constructor.
        /// </summary>
        internal static string SomeConstructorNode_Name {
            get {
                return ResourceManager.GetString("SomeConstructorNode_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to option.
        /// </summary>
        internal static string SomeConstructorNode_option_Name {
            get {
                return ResourceManager.GetString("SomeConstructorNode_option_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value.
        /// </summary>
        internal static string SomeConstructorNode_value_Name {
            get {
                return ResourceManager.GetString("SomeConstructorNode_value_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string StringAppend_Description {
            get {
                return ResourceManager.GetString("StringAppend_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Append To String.
        /// </summary>
        internal static string StringAppend_Name {
            get {
                return ResourceManager.GetString("StringAppend_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to slice.
        /// </summary>
        internal static string StringAppend_slice_in_Name {
            get {
                return ResourceManager.GetString("StringAppend_slice_in_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to slice.
        /// </summary>
        internal static string StringAppend_slice_out_Name {
            get {
                return ResourceManager.GetString("StringAppend_slice_out_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to string.
        /// </summary>
        internal static string StringAppend_string_in_Name {
            get {
                return ResourceManager.GetString("StringAppend_string_in_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to string.
        /// </summary>
        internal static string StringAppend_string_out_Name {
            get {
                return ResourceManager.GetString("StringAppend_string_out_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to combined string.
        /// </summary>
        internal static string StringConcat_combined_Name {
            get {
                return ResourceManager.GetString("StringConcat_combined_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string StringConcat_Description {
            get {
                return ResourceManager.GetString("StringConcat_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to first slice.
        /// </summary>
        internal static string StringConcat_firstSlice_in_Name {
            get {
                return ResourceManager.GetString("StringConcat_firstSlice_in_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to first slice.
        /// </summary>
        internal static string StringConcat_firstSlice_out_Name {
            get {
                return ResourceManager.GetString("StringConcat_firstSlice_out_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concatenate Strings.
        /// </summary>
        internal static string StringConcat_Name {
            get {
                return ResourceManager.GetString("StringConcat_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to second slice.
        /// </summary>
        internal static string StringConcat_secondSlice_in_Name {
            get {
                return ResourceManager.GetString("StringConcat_secondSlice_in_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to second slice.
        /// </summary>
        internal static string StringConcat_secondSlice_out_Name {
            get {
                return ResourceManager.GetString("StringConcat_secondSlice_out_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string StringFromSlice_Description {
            get {
                return ResourceManager.GetString("StringFromSlice_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String From Slice.
        /// </summary>
        internal static string StringFromSlice_Name {
            get {
                return ResourceManager.GetString("StringFromSlice_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to slice.
        /// </summary>
        internal static string StringFromSlice_slice_in_Name {
            get {
                return ResourceManager.GetString("StringFromSlice_slice_in_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to slice.
        /// </summary>
        internal static string StringFromSlice_slice_out_Name {
            get {
                return ResourceManager.GetString("StringFromSlice_slice_out_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to string.
        /// </summary>
        internal static string StringFromSlice_string_Name {
            get {
                return ResourceManager.GetString("StringFromSlice_string_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string StringToSlice_Description {
            get {
                return ResourceManager.GetString("StringToSlice_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String To Slice.
        /// </summary>
        internal static string StringToSlice_Name {
            get {
                return ResourceManager.GetString("StringToSlice_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to slice.
        /// </summary>
        internal static string StringToSlice_slice_Name {
            get {
                return ResourceManager.GetString("StringToSlice_slice_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to string.
        /// </summary>
        internal static string StringToSlice_string_Name {
            get {
                return ResourceManager.GetString("StringToSlice_string_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Subtract_Description {
            get {
                return ResourceManager.GetString("Subtract_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtract.
        /// </summary>
        internal static string Subtract_Name {
            get {
                return ResourceManager.GetString("Subtract_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x reference.
        /// </summary>
        internal static string Subtract_operand1Ref_in_Name {
            get {
                return ResourceManager.GetString("Subtract_operand1Ref_in_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x reference.
        /// </summary>
        internal static string Subtract_operand1Ref_out_Name {
            get {
                return ResourceManager.GetString("Subtract_operand1Ref_out_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y reference.
        /// </summary>
        internal static string Subtract_operand2Ref_in_Name {
            get {
                return ResourceManager.GetString("Subtract_operand2Ref_in_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y reference.
        /// </summary>
        internal static string Subtract_operand2Ref_out_Name {
            get {
                return ResourceManager.GetString("Subtract_operand2Ref_out_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x - y.
        /// </summary>
        internal static string Subtract_result_Name {
            get {
                return ResourceManager.GetString("Subtract_result_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TerminateLifetime_Description {
            get {
                return ResourceManager.GetString("TerminateLifetime_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminate Lifetime.
        /// </summary>
        internal static string TerminateLifetime_Name {
            get {
                return ResourceManager.GetString("TerminateLifetime_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UnwrapOptionTunnel_Description {
            get {
                return ResourceManager.GetString("UnwrapOptionTunnel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unwrap Option Tunnel.
        /// </summary>
        internal static string UnwrapOptionTunnel_Name {
            get {
                return ResourceManager.GetString("UnwrapOptionTunnel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string VectorCreate_Description {
            get {
                return ResourceManager.GetString("VectorCreate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Vector.
        /// </summary>
        internal static string VectorCreate_Name {
            get {
                return ResourceManager.GetString("VectorCreate_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vector.
        /// </summary>
        internal static string VectorCreate_vector_Name {
            get {
                return ResourceManager.GetString("VectorCreate_vector_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string VectorInsert_Description {
            get {
                return ResourceManager.GetString("VectorInsert_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to element reference.
        /// </summary>
        internal static string VectorInsert_element_Name {
            get {
                return ResourceManager.GetString("VectorInsert_element_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to index reference.
        /// </summary>
        internal static string VectorInsert_indexRef_in_Name {
            get {
                return ResourceManager.GetString("VectorInsert_indexRef_in_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to index reference.
        /// </summary>
        internal static string VectorInsert_indexRef_out_Name {
            get {
                return ResourceManager.GetString("VectorInsert_indexRef_out_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Into Vector.
        /// </summary>
        internal static string VectorInsert_Name {
            get {
                return ResourceManager.GetString("VectorInsert_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vector reference.
        /// </summary>
        internal static string VectorInsert_vectorRef_in_Name {
            get {
                return ResourceManager.GetString("VectorInsert_vectorRef_in_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vector reference.
        /// </summary>
        internal static string VectorInsert_vectorRef_out_Name {
            get {
                return ResourceManager.GetString("VectorInsert_vectorRef_out_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data reference.
        /// </summary>
        internal static string WriteStringToFileHandle_dataRef_in_Name {
            get {
                return ResourceManager.GetString("WriteStringToFileHandle_dataRef_in_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data reference.
        /// </summary>
        internal static string WriteStringToFileHandle_dataRef_out_Name {
            get {
                return ResourceManager.GetString("WriteStringToFileHandle_dataRef_out_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string WriteStringToFileHandle_Description {
            get {
                return ResourceManager.GetString("WriteStringToFileHandle_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file handle reference.
        /// </summary>
        internal static string WriteStringToFileHandle_fileHandleRef_in_Name {
            get {
                return ResourceManager.GetString("WriteStringToFileHandle_fileHandleRef_in_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file handle reference.
        /// </summary>
        internal static string WriteStringToFileHandle_fileHandleRef_out_Name {
            get {
                return ResourceManager.GetString("WriteStringToFileHandle_fileHandleRef_out_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write String To File Handle.
        /// </summary>
        internal static string WriteStringToFileHandle_Name {
            get {
                return ResourceManager.GetString("WriteStringToFileHandle_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Xor_Description {
            get {
                return ResourceManager.GetString("Xor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xor.
        /// </summary>
        internal static string Xor_Name {
            get {
                return ResourceManager.GetString("Xor_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x reference.
        /// </summary>
        internal static string Xor_operand1Ref_in_Name {
            get {
                return ResourceManager.GetString("Xor_operand1Ref_in_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x reference.
        /// </summary>
        internal static string Xor_operand1Ref_out_Name {
            get {
                return ResourceManager.GetString("Xor_operand1Ref_out_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y reference.
        /// </summary>
        internal static string Xor_operand2Ref_in_Name {
            get {
                return ResourceManager.GetString("Xor_operand2Ref_in_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y reference.
        /// </summary>
        internal static string Xor_operand2Ref_out_Name {
            get {
                return ResourceManager.GetString("Xor_operand2Ref_out_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x ^ y.
        /// </summary>
        internal static string Xor_result_Name {
            get {
                return ResourceManager.GetString("Xor_result_Name", resourceCulture);
            }
        }
    }
}
