//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rebar.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rebar.Resources.LocalizedStrings", typeof(LocalizedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebar Device.
        /// </summary>
        internal static string DeviceDisplayInfo_RebarTargetDisplayName {
            get {
                return ResourceManager.GetString("DeviceDisplayInfo_RebarTargetDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using this node requires a preview feature to be enabled..
        /// </summary>
        internal static string FeatureNotEnabled {
            get {
                return ResourceManager.GetString("FeatureNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebar.
        /// </summary>
        internal static string FeatureToggle_AllIntegerTypes_Category {
            get {
                return ResourceManager.GetString("FeatureToggle_AllIntegerTypes_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable support for all integer data types..
        /// </summary>
        internal static string FeatureToggle_AllIntegerTypes_Description {
            get {
                return ResourceManager.GetString("FeatureToggle_AllIntegerTypes_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebar.
        /// </summary>
        internal static string FeatureToggle_CellDataType_Category {
            get {
                return ResourceManager.GetString("FeatureToggle_CellDataType_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable the Cell data type and related nodes.
        /// </summary>
        internal static string FeatureToggle_CellDataType_Description {
            get {
                return ResourceManager.GetString("FeatureToggle_CellDataType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebar.
        /// </summary>
        internal static string FeatureToggle_FileHandleDataType_Category {
            get {
                return ResourceManager.GetString("FeatureToggle_FileHandleDataType_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable File Handle data type and related nodes.
        /// </summary>
        internal static string FeatureToggle_FileHandleDataType_Description {
            get {
                return ResourceManager.GetString("FeatureToggle_FileHandleDataType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebar.
        /// </summary>
        internal static string FeatureToggle_LLVMCompiler_Category {
            get {
                return ResourceManager.GetString("FeatureToggle_LLVMCompiler_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable LLVM-based compiler for Rebar execution target (requires enabling Rebar execution target).
        /// </summary>
        internal static string FeatureToggle_LLVMCompiler_Description {
            get {
                return ResourceManager.GetString("FeatureToggle_LLVMCompiler_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebar.
        /// </summary>
        internal static string FeatureToggle_OutputNode_Category {
            get {
                return ResourceManager.GetString("FeatureToggle_OutputNode_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable the Output node.
        /// </summary>
        internal static string FeatureToggle_OutputNode_Description {
            get {
                return ResourceManager.GetString("FeatureToggle_OutputNode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebar.
        /// </summary>
        internal static string FeatureToggle_RebarTarget_Category {
            get {
                return ResourceManager.GetString("FeatureToggle_RebarTarget_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable the Rebar execution target.
        /// </summary>
        internal static string FeatureToggle_RebarTarget_Description {
            get {
                return ResourceManager.GetString("FeatureToggle_RebarTarget_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebar.
        /// </summary>
        internal static string FeatureToggle_StringDataType_Category {
            get {
                return ResourceManager.GetString("FeatureToggle_StringDataType_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable string and string slice data types and related nodes.
        /// </summary>
        internal static string FeatureToggle_StringDataType_Description {
            get {
                return ResourceManager.GetString("FeatureToggle_StringDataType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebar.
        /// </summary>
        internal static string FeatureToggle_VectorAndSliceTypes_Category {
            get {
                return ResourceManager.GetString("FeatureToggle_VectorAndSliceTypes_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable vector and slice data types and related nodes.
        /// </summary>
        internal static string FeatureToggle_VectorAndSliceTypes_Description {
            get {
                return ResourceManager.GetString("FeatureToggle_VectorAndSliceTypes_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebar.
        /// </summary>
        internal static string FeatureToggle_VisualizeVariableIdentity_Category {
            get {
                return ResourceManager.GetString("FeatureToggle_VisualizeVariableIdentity_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable visualization of variable identities on wires.
        /// </summary>
        internal static string FeatureToggle_VisualizeVariableIdentity_Description {
            get {
                return ResourceManager.GetString("FeatureToggle_VisualizeVariableIdentity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function.
        /// </summary>
        internal static string FunctionDocumentType_DefaultDocumentName {
            get {
                return ResourceManager.GetString("FunctionDocumentType_DefaultDocumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebar Function.
        /// </summary>
        internal static string FunctionDocumentType_DisplayName {
            get {
                return ResourceManager.GetString("FunctionDocumentType_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebar Module.
        /// </summary>
        internal static string ModuleDisplayInfo_RebarModuleDisplayName {
            get {
                return ResourceManager.GetString("ModuleDisplayInfo_RebarModuleDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebar.
        /// </summary>
        internal static string RebarPaletteCategory_RebarPaletteDisplayName {
            get {
                return ResourceManager.GetString("RebarPaletteCategory_RebarPaletteDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This terminal cannot accept a wired immutable type..
        /// </summary>
        internal static string TerminalDoesNotAcceptImmutableType {
            get {
                return ResourceManager.GetString("TerminalDoesNotAcceptImmutableType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This terminal cannot accept a wired reference type..
        /// </summary>
        internal static string TerminalDoesNotAcceptReference {
            get {
                return ResourceManager.GetString("TerminalDoesNotAcceptReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lifetime of values wired to this node cannot be terminated with this node..
        /// </summary>
        internal static string TerminateLifetimeInputLifetimeCannotBeTerminated {
            get {
                return ResourceManager.GetString("TerminateLifetimeInputLifetimeCannotBeTerminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The values wired to this node do not all share the same lifetime..
        /// </summary>
        internal static string TerminateLifetimeInputLifetimesNotUnique {
            get {
                return ResourceManager.GetString("TerminateLifetimeInputLifetimesNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scope that this node terminates contains at least one variable that is not wired..
        /// </summary>
        internal static string TerminateLifetimeNotAllVariablesInLifetimeConnected {
            get {
                return ResourceManager.GetString("TerminateLifetimeNotAllVariablesInLifetimeConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data type connected to this terminal does not have the required trait: Display.
        /// </summary>
        internal static string TypeDoesNotHaveRequiredTrait {
            get {
                return ResourceManager.GetString("TypeDoesNotHaveRequiredTrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of value created by this terminal has not been fully determined..
        /// </summary>
        internal static string TypeNotDetermined {
            get {
                return ResourceManager.GetString("TypeNotDetermined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data type of this wire does not allow it to branch..
        /// </summary>
        internal static string WireCannotFork {
            get {
                return ResourceManager.GetString("WireCannotFork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reference wired to this terminal does not live long enough..
        /// </summary>
        internal static string WiredReferenceDoesNotLiveLongEnough {
            get {
                return ResourceManager.GetString("WiredReferenceDoesNotLiveLongEnough", resourceCulture);
            }
        }
    }
}
